### ISSUE TITLE
Error 'PoolConfig' object has no attribute 'pools'

### ISSUE THREAD

**Issue by wolmeh** [ghan1t/udev-trigger-zfs-autobackup#3]
Hi ghan1t,

thanks for working on the issues I reported. I have installed your updated script (fresh install) using your new config.yaml template but the scripts terminates with an error reporting _'PoolConfig' object has no attribute 'pools'_.

Do you know why?

Logfile attached.
[log.txt](https://github.com/ghan1t/udev-trigger-zfs-autobackup/files/14733579/log.txt)

**Comment by ghan1t** [comment]
@wolmeh sorry, I had introduced a bug with the latest change. It should be fixed now, but I couldn't fully test it as I'm not near my NAS to plugin a disk.
