### ISSUE TITLE
Error "name 'config' is not defined"

### ISSUE THREAD

**Issue by wolmeh** [ghan1t/udev-trigger-zfs-autobackup#4]
Hi ghan1t,

a new error occurs since your last update:

> An unexpected error occurred. Backup may have failed. Please investigate.
> 
> Error:
> name 'config' is not defined

[logfile.txt](https://github.com/ghan1t/udev-trigger-zfs-autobackup/files/14794379/logfile.txt)

**Comment by ghan1t** [comment]
@wolmeh sorry, I should really test things before pushing them - which I again didn't do as I just came home. If you want you can try with what I just pushed or wait until I tested it.

**Comment by ghan1t** [comment]
I'm trying it now, its still broken. I should really start using an IDE with some error checking
